
services:
  app:
    container_name: my_project_app
    build: .
    depends_on:
      - db
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0 --port 8000'
    volumes:
      - ./app:/src/app
    ports:
      - 8002:8000
    env_file:
      - .env
    
    
    

  db:
    container_name: my_project_db
    image: postgres:17.0-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5433:5432
    volumes:
      - .postgres:/var/lib/postgresql/data
    restart: always
    env_file:
      - .env